### ISSUE TITLE
AppleMusicNotificationReceiver なんでいるんだっけ

### ISSUE THREAD

**Issue by mataku** [mataku/SunsetScrob#18]
NotificationListenerService で通知バーから取得して, そこで処理すれば良さそうということに気付いてしまったけど, receiver で presenter 作って処理してるのはなんでなのか忘れた

**Comment by rhythnn** [comment]
https://github.com/rhythnn/ScrobScrob/pull/19 で雑にやろうとしてやめた. 

実態としていらなそうだけど, そもそもモデル設計とかがあれなのでそこをどうにかすることで, 本来目的としていた, 見通しが良くなる所を改善できるとかんがえられる
