### ISSUE TITLE
memo

### ISSUE THREAD

**Issue by mataku** [mataku/SunsetScrob#2]

**Comment by rhythnn** [comment]
setNowPlayingIfDifferentTrack メソッドが名前に対して重すぎる

**Comment by rhythnn** [comment]
最新X (ひとまず20) 件しか出さないようになっているので, 保存する件数もそれでよかだと思う

そもそも20件しか出してないのは
- 起動時にアートワークの画像を引っ張ってきているので通信が発生する ( URL のみこちらで保持 )
- scrobble した track を全部保存するのは容量的にあれなのではないか

**Comment by rhythnn** [comment]
署名されたリリースビルドの apk を勝手に作ってほしかったので, https://github.com/rhythnn/ScrobScrob/pull/21 にて (Bitrise 上で) 色々やった
https://mataku.com/2017/09/18/build-easily/
