### ISSUE TITLE
artist artwork

### ISSUE THREAD

**Issue by mataku** [mataku/SunsetScrob#465]
from last.fm support:

> Unfortunately we are unable to offer artist images and artwork through our API. It is stated in Clause 5.1.8 of our [Terms of Service](https://www.last.fm/api/tos):

Therefore, I should find out if any ways to acquire artwork in a rights-free manner...

**Comment by alpha4041** [comment]
Thanks a lot for creating this app! I like it :)
You can refer to this thread for this problem:
https://stackoverflow.com/questions/55978243/last-fm-api-returns-same-white-star-image-for-all-artists

**Comment by mataku** [comment]
Thanks for your information! It seems to be unstable and there are many unknowns, such as licensing issues, because it seems impossible to know what is in `relation`.

I will add the latest album artwork or via Spotify API under a clearly stated license to artist artwork.
